#!/bin/sh
#: Title       : Tmpclean
#: Date        : 2018-05-31
#: Author      : "Kybernetes" <correodelkybernetes@gmail.com>
#: Version     : 1.0.0
#: Description : Executable Dash shell script
#:             : Safely removes large ammounts of  files from temp. dirs using
#:             : * File types in names (a.k.a. extension);
#:             : * Mtime in minutes of each temp file;
#:             : Avoiding to remove files that are being used by a process.
#: Workflow    : For each directory in $_TMPDIRLST, and for each file type in
#:             : $_FTYPELST, it creates a file glob pattern that is expanded
#:             : and matching files passed as args. to a pipeline which first 
#:             : gets for each file its mtime in minutes since Epoch, and file's
#:             : full path, joining both in a sorted list. Then loops through 
#:             : that list, and if file's mtime is old enough (see $_MINSKEEP), 
#:             : tries to remove it only if file is not currently being used by 
#:             : another proc. The idea is that even for such a large number of
#:             : matching temp. files that a single pipeline won't be able to
#:             : handle them as args, it can still make it by splitting the task
#:             : in several pipelines (one for e/file type) for each temp. dir.
#: Options     : N/A
##
## -- Externals required for execution -----------------------------------------
type rm >/dev/null || exit 1    ## Remove files
type date >/dev/null || exit 1  ## Get system's time
type sleep >/dev/null || exit 1 ## Delay execution for some time
type ps >/dev/null || exit 1    ## Get current running procs
type stat >/dev/null || exit 1  ## Get file status
type fuser >/dev/null || exit 1 ## Identiry procs. using files
type timeout >/dev/null || exit 1
##
## -- Runtime config. ----------------------------------------------------------
_RPLY=            ## Internal read command reply;
# Declare the following useful symbols:
readonly _SP=" "  ## Space character (readonly uses word for assignment's LHS);
readonly _HT="	" ## Horizontal tab
readonly _LF="
"                 ## End of line (line feed)
# Script's name
_PRGNME=Tmpclean
# Execution blocking currently running instance's pid file
_PIDFILE=/tmp/${0##*/}.pid
# Allowed-to-clear extension EOL separation list
_FTYPELST=".[Pp][Dd][Ff]
.[Aa][Aa][Cc]
.[Oo][Dd][Tt]
.[Jj][Pp]*[Gg]
.[Pp][Nn][Mm]"
# Allowed-to-search EOL separated directory list
_TMPDIRLST="/usr/share/app1/tmpFileStorage
/usr/share/app2/tmpFileStorage
/usr/share/app3/tmpFileStorage"
# Temp. files max mtime to keep from now, in minutes
_MINSKEEP=180
# Temp. files removed for a given temp. dir
_TMPFLSRM=0
# Terminated by signal?
_SIGTRMND=false
##
## -- General purpose functions  -----------------------------------------------
stdmsg() { #@ DESCRIPTION: Print messages to STDOUT
           #@ USAGE: stdmsg [ MSG ... ]
    local time
    if [ "${1+X}" = X ]; then
        time=$(date +%T 2>/dev/null) || time=HH:MM:SS
        printf -- "==> [$time] %s\n" "$1"
        shift
        [ "${1+X}" != X ] || printf -- "               %s\n" "$@"
    fi
}
errmsg() { #@ DESCRIPTION: Print messages to STDERR prefixed by an error stamp
           #@ USAGE: stderr [ MSG ... ]
    stdmsg ${1+"Error! $@"} >&2
}
setvar() { #@ DESCRIPTION: Sets $1 variable specified by reference, to $2 value.
           #@ $1 MUST BE A VALID NAME!
           #@ USAGE: setvar NAME [ VALUE ]
           #@        /!\ - WARNING! - /!\ $1 must be a valid name
    eval "$1=\${2+\"\$2\"}" ## Without the right side backslash, escaped chars
                            ## won't be part of assignment
}
getvar() { #@ DESCRIPTION: Stores value of $2 referenced var in $1 name. If $2
           #@              referenced var. is unset, so $1 name will remain and
           #@              exit status will be 1.
           #@ USAGE: getvar NAMEW NAMER
           #@        /!\ - WARNING! - /!\ $1 AND $2 must be a valid names
    eval "[ \"\${$2+X}\" = X ] && $1=\"\${$2}\"" ## Do not set $1 referenced
                                                 ## name if $2 is also unset
}
_wqargs() { #@ DESCRIPTION: Weak-quotes all but the last argument, appending
            #@              them in order in last argument referenced name.
            #@ USAGE: _wqpprs [ ARG1 [ ARG2 .. ] ] NAME
            #@        /!\ - WARNINGS: - /!\
            #@        * Last arg. must be a valid name
            #@        * DO NOT CALL DIRECTLY, use below wrapper instead.
    # Local variables ("local" must be function's first statement)
    local qtd ## Last quoted args string temporary storage
    while [ $# -gt 1 ]; do       ## While this is not the last arg..
        eval "getvar qtd \${$#}" ## Save last arg. referenced string
        ## Rewrite last arg. ref. string w/temp. +space +quoted current arg.
        eval "setvar \${$#} \${qtd:+\"\$qtd \"}\\\"\"\$1\"\\\""
        shift                  ## Remove current arg from list
    done
}
wqargs() { #@ DESCRIPTION: Weak-quotes all but 1st arg., storing them in order
           #@              in the 1st arg. referenced name using _wqargs().
           #@              Useful for building cmds in variables during runtime.
           #@ USAGE: NAME [ ARG1 [ ARG2 .. ] ]
           #@        /!\ - WARNING! - /!\ $1 must be a valid name
    # Local variables ("local" must be function's first statement)
    local _$1            ## Prefix name to safely pass it to wrapped function
    eval "getvar _$1 $1" ## Store previous content of $1 referenced name
    set -- "$@" _$1      ## Append name at the end as required by wrapped func.
    shift                ## Now safely remove first arg
    _wqargs "$@"         ## Issue wrapped function passing all args and name
    eval "getvar \${$##_} \${$#}" ## $1 is no longer initial name after shift,
                                  ## so access _$1 w/var. exp. before assigning.
}
tmout() { #@ DESCRIPTION: Execute command w/a timeout upon whose expiration
          #@              SIGKILL is sent to the process. If that is blocked,
          #@              then subsequent SIGKILL will attempt to terminate it
          #@              after a certain delay.
          #@ USAGE: tmout SECS COMMAND
    # Local variables ("local" must be function's first statement)
    local tout cmd=
    tout=$1                       ## Get first pos. par. as seconds to timeout
    shift 1                       ## Remove it
    wqargs cmd ${1+"$@"}
    shift $#
    sh -c "{                      ## Start killer process in backgnd
set -m                            ## Enable job control
intvl=1 dly=2 tout=$tout          ## Initialize interval, delay and timeout
while [ \$tout -gt 0 ]; do        ## While we still have time
    if ! ps -o pid -p \$$; then   ## Frgnd proc running? ($$ expnds before back)
        wait \$$                  ## No, so wait to capture exit status
        exit \$?                  ##     Exit w/foreground's exit stat
    fi                            ## Yes, so..
    sleep \$intvl                 ## * Sleep for interval before asking again
    tout=\$((tout - intvl))       ## * Decrease timeout
done                              ## Out of time, and killer will do it's job
    kill -s TERM \$$              ## Try to TERM foreground process
    sleep \$dly                   ## Delay the KILL a bit
    if ps -o pid -p \$$; then     ## Is foreground still running?
        kill -s KILL \$$          ## Yes, so kill it
        sleep \$dly               ## Await before checking again
        if ps -o pid -p \$$; then ## If it still running then..
            exit 3                ## Finish w/distinctive error
        fi                        
        exit 2                    ## Process didn't TERMINATED but KILLED
    fi
    exit 1                        ## Process TERMINATED
} >/dev/null 2>&1 &               ## Fork nullifying output
exec $cmd"                        ## Replace foreground execution w/command's
}
_TMPFFID=0  ## Unique incremental temporary fifo ID
_mkTFfo() { #@ DESCRIPTION: Creates single temp fifo in /tmp for each invocation
            #@              during current instance of script updating unique
            #@              global ID and storing full path in $1 name.
            #@ USAGE: _mkTFfo NAME
            #@        /!\ - WARNINGS: - /!\
            #@        * $1 must be a valid name
            #@        * DO NOT CALL DIRECTLY, use mkTFfo() wrapper instead.
    # Local variables ("local" must be function's first statement)
    local n tffpth
    # Initialize fifo's path and an attempts counter
    tffpth=/tmp/${0##*/}.$$.$_TMPFFID.tmp n=0
    # Try create while fifo exists, limiting attempts number
    while ! mkfifo "$tffpth" 1>/dev/null 2>&1 && [ $n -lt 100 ]; do
        if [ -e $tffpth ]; then                             ## Ffo lready there?
            _TMPFFID=$((_TMPFFID < 999 ? _TMPFFID + 1 : 0)) ## Yes, increase ID
            tffpth=/tmp/${0##*/}.$$.$_TMPFFID.tmp           ## and set new path
        else                                                ## No, so problem
            errmsg "Failed to create named pipe"            ## Display error msg
            return 1                                        ## Report to calling
        fi                                                  ## environment.
        n=$((n + 1))                                ## Increase attempts counter
    done                                            ## Now sure that ffo exists
    _TMPFFID=$((_TMPFFID < 999 ? _TMPFFID + 1 : 0)) ## Increase global ID
    if [ $n -gt 100 ]; then                         ## Loop finished by limit?
        errmsg "Too many named pipes"               ## Assume too many fifos
        return 2                                    ## Finish w/errors
    fi
    setvar $1 "$tffpth"
}
mkTFfo() { #@ DESCRIPTION: Creates single temp fifo in /tmp using _mkTFfo()
           #@ USAGE: mkTFfo NAME
    # Local variables ("local" must be function's first statement)
    local _$1                ## Create prefixed storage for wrapped output
    _mkTFfo _$1 || return $? ## Call wrapped or finish preserving error status
    getvar $1 _$1            ## Set referenced name w/wrapped output
}
##
## -- Script specific functions  -----------------------------------------------
readPIDF() { #@ DESCRIPTION: Tries to read a valid PID from pidfile in $2 path,
             #@              storing read pid in $1 name on success.
             #@ USAGE: readPIDF NAME [ PATH ]
    IFS= read -r _RPLY <"${2:-/tmp/${0##*/}.pid}"
    case $? in
        1)        ## EOF reached
            if [ "X$_RPLY" = X ]; then ## EOF reached before EOL?
                errmsg "Failed to read from PIDfile ${2:-/tmp/${0##*/}.pid}"
                return 1               ## Finish w/errors
            fi ;; ## Now sure that we read something from file, so check it
        [!0]*)    ## Something went wrong while reading file
            errmsg "Unable to read from PIDfile ${2:-/tmp/${0##*/}.pid}"
            return 1 ;;
    esac
    case $_RPLY in     
        0|1|*[!0-9]*)   ## Did we get a valid PID
            errmsg "Bad PID read from PIDfile ${2:-/tmp/${0##*/}.pid}"
            return 1 ;; ## Finish w/errors
    esac                ## Now sure that numeric PID read from file
    setvar $1 $_RPLY    ## Write read PID to referenced name            

}
end() { #@ DESCRIPTION: Finishes exec. correctly, cleaning up files, displaying
        #@              remaining information and exiting from program w/$1
        #@              specified exit status. It also adds support for handling
        #@              signals.
        #@ USAGE: end INT
    # Try to remove all /tmp/${0##*/}.$$.*.tmp fifos
    rm -f /tmp/${0##*/}.$$.*.tmp
    # Try to remove pidfile
    rm -f "$_PIDFILE" >/dev/null 2>&1
    if [ -e "$_PIDFILE" ]; then
        errmsg "Failed to remove pidfile."
    fi
    # Report partially removed files ammount
    if $_SIGTRMND && [ $_TMPFLSRM -gt 0 ]; then
        printf "\n"
        stdmsg "Partially removed $_TMPFLSRM files."
    fi
    # Finish w/given exit status
    stdmsg "$_PRGNME finishes."
    printf "\n"
    exit $1

}
prntspnr() { #@ DESCRIPTION: Print a char according to $1 int. value, returning
             #@              cursor to its original position after printing,
             #@              overwriting it upon subsequent calls. This creates
             #@              the illusion of a spinning bar on the screen.
             #@ USAGE: prntspnr [ INT ]
    # Local variables ("local" must be function's first statement)
    local c fmt='\033[s==> %s\033[u' ## Char to show and format w/cursor mvment.
    case $(($1%4)) in                ## Select one of only 4 positions
        0) c=- ;;
        1) c='\' ;;
        2) c='|' ;;
        3) c=/ ;;
    esac
    printf "$fmt" $c                 ## Display char.
}
##
## -- Main ---------------------------------------------------------------------
main() {
    # Local variables ("local" must be function's first statement)
    local tdy ctdir ftyplst cftyp pttrn tffo ftchpid nowsecs cfile flesecs \
          dpid s
    tdy=$(date +"%Y-%m-%d" 2>/dev/null) || tdy=yyyy-mm-dd
    stdmsg "$tdy $_PRGNME starts"
    # Additional runtime configuration
    stdmsg "Loading configuration.."
    IFS=$_SP$_HT$_LF  ## Reset IFS as it should be by default
    umask 077         ## Allow only owner to access created files
    unalias -a        ## Destroy any alias that may change externals execution
    set -m            ## Force job control ON
    sleep 1
    # Check for already running instance
    stdmsg "done."
    stdmsg "Checking for already running instance.."
    if [ -e "$_PIDFILE" ]; then
        readPIDF pid "$_PIDFILE" &&
            errmsg "$_PRGNME is already running on PID=$pid" ||
                errmsg "Another instance of $_PRGNAME could be running."
        return 1
    fi
    sleep 1
    stdmsg "Done."
    # Try create pidfile
    stdmsg "Creating pidfile.."
    if ! printf "%d\n" $$ >"${_PIDFILE:-/tmp/${0##*/}.pid}"; then
        errmsg "Failed to create pidfile ${_PIDFILE:-/tmp/${0##*/}.pid}"
        return 2
    fi
    sleep 1
    stdmsg "Done."
    # Start signal traps
    stdmsg "Starting traps.."
    trap 'printf "\nTerminated by signal!"; _SIGTRMND=true; end 3' INT TERM KILL
    sleep 1
    stdmsg "Done."
    ## Try get now seconds since epoc
    if ! nowsecs=$(date +%s 2>/dev/null); then
        errmsg "Unable to get now seconds since epoch"
        end 3
    fi    
    # Process all elements from directory list
    while [ "X$_TMPDIRLST" != X ]; do    ## Still have temp dirs in list?
        ctdir=${_TMPDIRLST%%$_LF*}       ## Get curr. dir from list
        ftyplst=$_FTYPELST               ## Reset local file type list
        if [ -d "$ctdir" ]; then         ## Skip if not existent
            stdmsg "Cleaning files for $ctdir.."
            # Fetch files for each file type from list
            while [ "X$ftyplst" != X ]; do     ## Still have types in list?
                cftyp=${ftyplst%%$_LF*}        ## Get currt type from list
                pttrn="\"$ctdir\"/*$cftyp" ## Set pattern for matching files
                _TMPFLSRM=0                    ## Reset rm files cntr. for type
                stdmsg "Fetching *$cftyp files sorted by mtime.."
                ## Try Create a temp fifo to store results
                if ! mkTFfo tffo; then  
                    errmsg "Unable to create a temporary pipe"
                    end 3            ## Fail if not able to
                fi
                ## Expand pttrn before passing matching fles to stat. Don't mind
                ## if it fails due to limited access or non-existing, just list
                ## if able. Then pipe result to sort files by first field, which
                ## is mtime seconds since epoch. Also discard any error messages
                { eval "stat -c \"%Y$_HT%n\" -- $pttrn" |
                        sort -nt "$_HT" -k 1,1 >$tffo; } 2>/dev/null &
                ftchpid=$!
                sleep 1
                stdmsg "Removing older than ${_MINSKEEP:-0} minutes.."
                ## Start background dummy to later check elapsed time
                { sleep 2 & } 2>/dev/null
                dpid=$! s=0 ## Get dummy's pid and reset spinner counter
                ## Read from named pipe line by line
                { while IFS= read -r _RPLY; do
                      flesecs=${_RPLY%%$_HT*}  ## Get mtime from first col
                      cfile=${_RPLY#*$_HT}     ## Get path from second col
                      if [ -f "$cfile" ]; then ## If not regular file, skip
                          case $flesecs in     ## if invalid mtime format, skip
                              "" | *[!0-9]*) continue ;;
                          esac               ## Is current file in remove range?
                          if [ $(((nowsecs - flesecs)/60)) -gt ${_MINSKEEP:-0} ]
                          then               ## Yes so..
                              tmout 1 fuser -f "$cfile" ## Chk. if used or tmout
                              case $? in                ## Skip if above fails
                                  1)                    ## File is not used?
                                      rm -f "$cfile"      ## Try remove, if
                                      [ ! -e "cfile" ] && ## removed count
                                          _TMPFLSRM=$((_TMPFLSRM + 1)) ;;
                              esac
                          else              ## No, so as files are time-sorted,
                              break         ## remaining ones are to be skipped
                          fi
                      fi
                      ## As per backgrounded dummy, Is time to display spinner?
                      if ! ps -o pid -p $dpid >/dev/null 2>&1
                      then                                     ## If dummy died
                          prntspnr $s                          ## Display
                          { sleep 2 & } 2>/dev/null            ## Spawn new
                          dpid=$!                              ## Reset pid
                          s=$((s + 1))                         ## inc. counter
                      fi
                  done <$tffo; } 2>/dev/null
                stdmsg "Done." "Files removed: $_TMPFLSRM"                
                wait $ftchpid ||       ## Catch exit status of fetch process
                    [ $? -lt 127 ] &&  ## Report only fetch errors
                        errmsg "Failure while fetching softed file list"
                rm -f $tffo               ## Remove no longer needed fifo
                case $ftyplst in          ## Does types list contain an EOL?
                    *$_LF*) ftyplst=${ftyplst#*$_LF} ;; ## Yes, rm any char
                    *) ftyplst= ;;                      ## up to it;
                esac                                    ## No, assume end of
            done                                        ## list reached.
            # Now fetch all remaining non-matching files        
            pttrn="\"$ctdir\"/*" ## Set pattern for matching remaining files
            _TMPFLSRM=0          ## Reset removed files counter
            stdmsg "Fetching remaining files sorted by mtime.."
            ## Try Create a temp fifo to store results
            if ! mkTFfo tffo; then  
                errmsg "Unable to create a temporary pipe"
                end 3            ## Fail if not able to
            fi
            ## Expand pattern before passing matching files to stat, then pipe
            ## results to sort as before.
            { eval "stat -c \"%Y$_HT%n\" -- $pttrn" |
                    sort -nt "$_HT" -k 1,1 >$tffo; } 2>/dev/null &
            ftchpid=$!
            stdmsg "Removing older than ${_MINSKEEP:-0} minutes.."
            ## Process output from named pipe as before
            { sleep 2 & } 2>/dev/null
            dpid=$! s=0
            { while IFS= read -r _RPLY; do
                  flesecs=${_RPLY%%$_HT*}  ## Get file's mtime from first col
                  cfile=${_RPLY#*$_HT}     ## Get file's path from second col
                  if [ -f "$cfile" ]; then ## If not regular file, skip
                      case $flesecs in     ## if invalid mtime format, skip
                          "" | *[!0-9]*) continue ;;
                      esac                 ## Is current file in remove range?
                      if [ $(((nowsecs - flesecs)/60)) -gt ${_MINSKEEP:-0} ]
                      then                 ## Yes so..
                          tmout 1 fuser -f "$cfile" ## Check if used for a while
                          case $? in                ## Skip if above fails
                              1)                    ## If file is not being used
                                  rm -f "$cfile"       ## Try to remove file
                                  [ ! -e "cfile" ] &&  ## If removed count
                                      _TMPFLSRM=$((_TMPFLSRM + 1)) ;;
                          esac
                      else                 ## No, so as files are time-sorted,
                          break            ## remaining ones are to be skipped
                      fi
                  fi
                  ## As per backgrounded dummy, Is it time to display spinner?
                  if ! ps -o pid -p $dpid >/dev/null 2>&1; then ## If dummy died
                      prntspnr $s                               ## Display
                      { sleep 2 & } 2>/dev/null                 ## Spawn new
                      dpid=$!                                   ## Reset pid
                      s=$((s + 1))                              ## inc. counter
                  fi
              done <$tffo; } 2>/dev/null
            stdmsg "Done." "Files removed: $_TMPFLSRM"
            wait $ftchpid ||       ## Catch exit status of fetch process
                [ $? -lt 127 ] &&  ## Report only fetch errors
                    errmsg "Failure while fetching softed file list"
            rm -f $tffo            ## Remove no longer needed fifo
        fi
        stdmsg "Done."
        ## Continue w/next directory
        case $_TMPDIRLST in            ## Does tmp files list contain an EOL?
            *$_LF*) _TMPDIRLST=${_TMPDIRLST#*$_LF} ;; ## Yes, rm all up to it
            *) _TMPDIRLST= ;;                         ## No, assume end of list
        esac
    done
    end 0
}
##
## -- Run! ---------------------------------------------------------------------
main
